default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: Cinema_Suggestion_development
test:
  <<: *default
  database: Cinema_Suggestion_test
production:
  <<: *default
  database: Cinema_Suggestion_production
  username: Cinema_Suggestion
  password: <%= ENV['CINEMA_SUGGESTION_DATABASE_PASSWORD'] %>
